name: CI - PR

on:
  pull_request:

jobs:
  Tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.2', '8.3']

    steps:
      - name: "Init repository"
        uses: actions/checkout@v4

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: imap
          tools: composer

      - name: "Install dependencies"
        run: composer install

      - name: "Tests"
        run: php vendor/bin/phpunit tests --whitelist src --coverage-clover ./build/logs/clover.xml

